FROM    nginx

COPY    nginx/default.conf /etc/nginx/conf.d/
COPY    nginx/login.html /usr/share/nginx/html/
COPY    nginx/logout.html /usr/share/nginx/html/
COPY    nginx/register.html /usr/share/nginx/html/
COPY    nginx/table.css /usr/share/nginx/html/
COPY    nginx/board.css /usr/share/nginx/html/
COPY    nginx/login.css /usr/share/nginx/html/
COPY    nginx/register.css /usr/share/nginx/html/
COPY    nginx/504.html /usr/share/nginx/html/
ADD     nginx/temp /usr/share/nginx/html/
LABEL   tag="harbor.chaihy.xyz/test/nginx:latest"
EXPOSE  80
